version: '3.1'
services:
  postgresdb:
    image: postgres:alpine
    container_name: postgres_container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.cl
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
        - ./pgadmin:/root/.pgadmin
    restart: always
    ports:
      - "5433:80"
    
    
      #docker-compose down --remove-orphans
      #docker-compose up --build